export type Line = "RED" | "YELLOW" | "BLUE" | "GREEN" | "VIOLET" | "PINK" | "ORANGE" | "MAGENTA" | "GREY" | "AQUA" | "RAPID";




const lineToStationMapping: Record<Line, string[]> = {
    RED: [
        "RITHALA", "ROHINI WEST", "ROHINI EAST", "PITAMPURA", "NETAJI SUBHASH PLACE",
        "KESHAV PURAM", "KANHAIYA NAGAR", "INDERLOK", "SHASTRI NAGAR", "PRATAP NAGAR",
        "PULBANGASH", "TIS HAZARI", "KASHMERE GATE", "SHASTRI PARK", "SEELAMPUR",
        "WELCOME", "SHAHDARA", "MANSAROVAR PARK", "JHILMIL", "DILSHAD GARDEN",
        "SHAHEED NAGAR", "RAJ BAGH", "MOHAN NAGAR", "ARTHALA", "HINDON RIVER",
        "SHAHEED STHAL ( NEW BUS ADDA)"
    ],

    YELLOW: [
        "SAMAYPUR BADLI", "AZADPUR", "MODEL TOWN", "VISHWAVIDYALAYA", "VIDHAN SABHA",
        "CIVIL LINES", "CHANDNI CHOWK", "CHAWRI BAZAR", "NEW DELHI (Yellow & Airport Line)",
        "RAJIV CHOWK", "PATEL CHOWK", "CENTRAL SECRETARIAT", "UDYOG BHAWAN",
        "LOK KALYAN MARG", "JOR BAGH", "DILLI HAAT - INA", "AIIMS", "GREEN PARK",
        "HAUZ KHAS", "MALVIYA NAGAR", "SAKET", "QUTAB MINAR", "CHHATARPUR",
        "SULTANPUR", "GHITORNI", "ARJAN GARH", "GURU DRONACHARYA", "SIKANDERPUR",
        "M.G. ROAD", "IFFCO CHOWK", "MILLENNIUM CITY CENTRE GURUGRAM"
    ],

    BLUE: [
        "DWARKA SECTOR - 21", "DWARKA SECTOR - 8", "DWARKA SECTOR - 9", "DWARKA SECTOR - 10",
        "DWARKA SECTOR - 11", "DWARKA SECTOR - 12", "DWARKA SECTOR - 13",
        "DWARKA SECTOR - 14", "DWARKA MOR", "JANAKPURI WEST", "JANAKPURI EAST",
        "TILAK NAGAR", "SUBHASH NAGAR", "TAGORE GARDEN", "RAJOURI GARDEN",
        "RAMESH NAGAR", "MOTI NAGAR", "KIRTI NAGAR", "SHADIPUR", "PATEL NAGAR",
        "RAJENDRA PLACE", "KAROL BAGH", "JHANDEWALAN", "RAMAKRISHNA ASHRAM MARG",
        "RAJIV CHOWK", "BARAKHAMBA ROAD", "MANDI HOUSE", "PRAGATI MAIDAN",
        "INDRAPRASTHA", "YAMUNA BANK", "AKSHARDHAM", "MAYUR VIHAR -I",
        "MAYUR VIHAR EXTENSION", "NEW ASHOK NAGAR", "NOIDA SECTOR-15",
        "NOIDA SECTOR-16", "NOIDA SECTOR-18", "BOTANICAL GARDEN",
        "GOLF COURSE", "NOIDA CITY CENTRE", "SECTOR - 34 NOIDA", "SECTOR - 52 NOIDA",
        "SECTOR - 59 NOIDA", "SECTOR - 61 NOIDA", "SECTOR - 62 NOIDA",
        "NOIDA ELECTRONIC CITY", "VAISHALI", "KAUSHAMBI", "ANAND VIHAR ISBT"
    ],

    GREEN: [
        "INDERLOK", "ASHOK PARK MAIN", "SATGURU RAM SINGH MARG", "KIRTI NAGAR",
        "MADIPUR", "PASCHIM VIHAR EAST", "PASCHIM VIHAR WEST", "PEERAGARHI",
        "UDYOG NAGAR", "MAHARAJA SURAJMAL STADIUM", "NANGLOI", "NANGLOI RAILWAY STATION",
        "RAJDHANI PARK", "MUNDKA", "MUNDKA INDUSTRIAL AREA (MIA)",
        "GHEVRA METRO STATION", "TIKRI KALAN", "TIKRI BORDER",
        "BRIG. HOSHIAR SINGH", "BAHADURGARH CITY"
    ],

    VIOLET: [
        "KASHMERE GATE", "LAL QUILA", "JAMA MASJID", "DELHI GATE", "ITO",
        "MANDI HOUSE", "JANPATH", "CENTRAL SECRETARIAT", "KHAN MARKET",
        "JLN STADIUM", "JANGPURA", "LAJPAT NAGAR", "MOOLCHAND", "KAILASH COLONY",
        "NEHRU PLACE", "KALKAJI MANDIR", "GOVIND PURI", "OKHLA NSIC",
        "SUKHDEV VIHAR", "JAMIA MILLIA ISLAMIA", "OKHLA VIHAR", "JASOLA VIHAR SHAHEEN BAGH",
        "KALINDI KUNJ", "OKHLA BIRD SANCTUARY", "BOTANICAL GARDEN"
    ],

    PINK: [
        "MAJLIS PARK", "AZADPUR", "SHALIMAR BAGH", "NETAJI SUBHASH PLACE",
        "SHAKURPUR", "PUNJABI BAGH WEST", "ESI-BASAIDARAPUR", "RAJOURI GARDEN",
        "MAYAPURI", "NARAINA VIHAR", "DELHI CANTT.", "DURGABAI DESHMUKH SOUTH CAMPUS",
        "SIR M. VISHWESHWARAIAH MOTI BAGH", "BHIKAJI CAMA PLACE", "SAROJINI NAGAR",
        "SOUTH EXTENSION", "LAJPAT NAGAR", "VINOBAPURI", "ASHRAM",
        "SARAI KALE KHAN - NIZAMUDDIN", "MAYUR VIHAR POCKET-1",
        "TRILOKPURI-SANJAY LAKE", "EAST VINOD NAGAR-MAYUR VIHAR -II",
        "MANDAWALI - WEST VINOD NAGAR", "I.P. EXTENSION", "KARKARDUMA",
        "KARKARDUMA COURT", "ANAND VIHAR ISBT", "SHAHDARA"
    ],

    ORANGE: [
        "NEW DELHI (Yellow & Airport Line)", "SHIVAJI STADIUM",
        "DELHI AEROCITY", "AIRPORT (T-3)", "DWARKA SECTOR - 21"
    ],

    MAGENTA: [
        "JANAKPURI WEST", "DABRI MOR - JANAKPURI SOUTH", "DASHRATHPURI", "PALAM",
        "SADAR BAZAR CANTONMENT", "TERMINAL 1-IGI AIRPORT", "SHANKAR VIHAR",
        "VASANT VIHAR", "MUNIRKA", "R.K.PURAM", "IIT", "HAUZ KHAS",
        "PANCHSHEEL PARK", "CHIRAG DELHI", "GREATER KAILASH", "NEHRU ENCLAVE",
        "KALKAJI MANDIR", "OKHLA NSIC", "SUKHDEV VIHAR", "JAMIA MILLIA ISLAMIA",
        "OKHLA VIHAR", "JASOLA-APOLLO", "SARITA VIHAR", "MOHAN ESTATE",
        "TUGHLAKABAD STATION", "BADARPUR BORDER"
    ],

    GREY: [
        "DWARKA", "NANGLI", "NAJAFGARH", "DHANSA BUS STAND"
    ],

    AQUA: [
        "SECTOR - 51", "SECTOR - 50", "SECTOR - 76", "SECTOR - 101",
        "SECTOR - 81", "NSEZ", "NOIDA SECTOR-52", "NOIDA ELECTRONIC CITY"
    ],

    RAPID: ["SHANKAR VIHAR"],



}


export function linefilter(Line: Line) {
    const totlalStations = lineToStationMapping[Line] || [];
    return totlalStations;

}







